### PR TITLE
Fix at-loader errors for d.ts files

### LINKED ISSUE #194: at-loader errors for d.ts files
Hi,
typescript loader gives me these errors when I use aurelia-form with the typescript-webpack navigation skeleton. The aurelia app works fine.

> webpack: Compiled successfully.
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:216:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:216:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:218:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:219:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:219:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:221:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:222:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:222:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:224:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:225:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:225:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:227:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:228:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:228:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:230:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:231:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:231:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:233:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:234:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:234:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:236:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:237:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:237:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:239:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:240:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:240:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:242:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:243:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:243:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:245:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:246:1
>     TS1128: Declaration or statement expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:246:16
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:248:8
>     TS1005: ';' expected.
> 
> [at-loader] ./node_modules/aurelia-config/dist/aurelia-config.d.ts:24:16
>     TS1030: 'export' modifier already seen.
> 
> [at-loader] ./node_modules/aurelia-config/dist/aurelia-config.d.ts:49:2
>     TS1036: Statements are not allowed in ambient contexts.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:6:9
>     TS2305: Module '"C:/Git/pappt/aurelia-form-demo-typescript-webpack/node_modules/aurelia-config/dist/aurelia-config"' has no exported member 'Configuration'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:10:15
>     TS2307: Cannot find module 'aurelia-form/decorator/index'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:216:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:218:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:219:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:221:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:222:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:224:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:225:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:227:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:228:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:230:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:231:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:233:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:234:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:236:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:237:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:239:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:240:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:242:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:243:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:245:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:246:8
>     TS2304: Cannot find name 'declare'.
> 
> [at-loader] ./node_modules/aurelia-form/dist/aurelia-form.d.ts:248:3
>     TS2304: Cannot find name 'from'.
> 
> [at-loader] ./node_modules/aurelia-view-manager/dist/aurelia-view-manager.d.ts:87:31
>     TS2304: Cannot find name 'ViewEngine'.
> 
> [at-loader] ./node_modules/aurelia-view-manager/dist/aurelia-view-manager.d.ts:87:63
>     TS2304: Cannot find name 'ViewCompileInstruction'.
> 
> [at-loader] ./node_modules/aurelia-view-manager/dist/aurelia-view-manager.d.ts:87:101
>     TS2304: Cannot find name 'ResourceLoadContext'.
> 
> [at-loader] ./node_modules/aurelia-view-manager/dist/aurelia-view-manager.d.ts:87:131
>     TS2304: Cannot find name 'ViewFactory'.

### PR DESCRIPTION
**Pull request by jvkassi**
Hi,

@RWOverdijk, this PR should fix https://github.com/SpoonX/aurelia-form/issues/194

I managed to remove all the errors.
I had to concat all files using:
```
    concat: true,
```
in the file spoonx.js

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@mib4fun I'm not entirely convinced on the solution, it seems a bit odd. Do you know why it works this way?

If it does, and there's a good reason for it, this is really cool! But we'd have to carefully test it. :)

**Comment by jvkassi** [comment]
Typescript does not support es6 export https://github.com/TypeStrong/typedoc/issues/100
This line here https://github.com/SpoonX/aurelia-form/blob/master/src/aurelia-form.js#L6 was causing the issue.

I had to remove it but then i have to set "concat: true" to export all the decorators.
Adding some tests is never a bad idea

**Comment by RWOverdijk** [comment]
@mib4fun would you mind adding those? it's too much of a gamble to just merge :)

**Comment by jvkassi** [comment]
@RWOverdijk , yeah no problem, but i might take me a bit of the time. Can someone look into this as well ?

**Comment by jvkassi** [comment]
Will unit tests be enough ?

**Comment by RWOverdijk** [comment]
@mib4fun I'll install this version in my dashboard, see if it still works. :)

**Comment by jvkassi** [comment]
@RWOverdijk thanks :crossed_fingers:

**Comment by RWOverdijk** [comment]
@mib4fun This seems to work for me, have you been testing this, too?

**Comment by jvkassi** [comment]
@RWOverdijk  yeah good for me too !

**Comment by RWOverdijk** [comment]
I'll make this a pre-release just in case :)

**Comment by RWOverdijk** [comment]
@mib4fun aurelia-form@1.3.2-0

**Comment by jvkassi** [comment]
@RWOverdijk thanks ! You're the best

**Pull request merged**
