### PR TITLE
missing resource in spoonx.js and incorrect import from metadata in entity-form

### PR DESCRIPTION
**Pull request by bzd2000**
fix (spoonx.js): add form-checkbox to jsResources in order to be concatenated
fix (entity-form.js): correct the import of Metadata from ../aurelia-form instead of ../metadataadata

### CODE REVIEW

**Comment by bzd2000** [comment]
Strange that the test failed, on my machine they were OK.
Something i need to do?

**Comment by RWOverdijk** [comment]
What does this solve? I'm sorry I don't have a clear memory on this issue.

**Comment by bzd2000** [comment]
2 errors:  
wrong reference to metadata in entity-form (it is in aurela-form  and not as a single file)
form-checkbox not in spoonx.js, so it doesn't exists as a seperate file

In fact the plugin is not usable when you install it from scratch
It fails when loaded in the browser

**Comment by M2Mark** [comment]
Version 1.3.2-0 is not working. I have verified that the fix as attached to this pull request is working. Can you please merge this one in to a new version of the package a.s.a.p.?

**Comment by bzd2000** [comment]
Yes, but i think Wesley needs to approve it first

**Comment by RWOverdijk** [comment]
Would you all be fine with another prerelease to test this? I don't want to break any other packages.

**Comment by RWOverdijk** [comment]
Also for some reason the tests appear to be failing. I'm rerunning them now to verify.

**Comment by RWOverdijk** [comment]
Still failing... I do feel like this is related to the other failing test suites.

**Comment by bzd2000** [comment]
But the current version is broken.
I don't understand how others are able to use this plugin

**Comment by RWOverdijk** [comment]
The current version is a prerelease. It's a prerelease for that exact reason (to not break existing projects).

The fact that it's broken is not enough reason to potentially break it even more I'd say.

I'll merge this and then create an issue to figure out what's wrong with the tests.

**Comment by RWOverdijk** [comment]
Published.

**Comment by M2Mark** [comment]
Thank you very much for the effort to create a pre-release :)

**Comment by RWOverdijk** [comment]
No effort at all. I want this to work as much as you do :D

**Pull request merged**
