### PR TITLE
fix: aurelia build resources (webpack)

### PR DESCRIPTION
**Pull request by t03apt**
Hi,

I have been integrating aurelia-form plugin with the aurelia typescript-webpack [skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack).

I have been getting this error: Error: Cannot find module './aurelia-form/attribute/prefixed' https://www.screencast.com/t/skQssHxaLAL

I have added some explicit resources to [my package.json](https://gitlab.com/t03apt/aurelia-form-demo-typescript-webpack/blob/master/package.json) what solved the issue.

I think this PR fixes the issue so that as an external developer I don't need to add these explicit resources to my package.json.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@t03apt Don't wildcards work? It complains about attribute, so maybe add: `aurelia-form/attribute/**/*`, then we wouldn't need the full list?

**Update:** If it's not too much effort, could you change your commit message to adhere to our [guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)? Something like this:

> `	fix(project): add resources`

**Comment by t03apt** [comment]
@RWOverdijk Wildcard did not work for me. At the [bottom you can see](https://www.screencast.com/t/skQssHxaLAL) it was complaining about elements within aurelia-form/component/ too.

I have renamed the commit.

**Comment by RWOverdijk** [comment]
That's too bad... In any case, thank you a lot.

Note for the future (I'll make tickets for it):

- Add a test to verify all the resources have been defined, to make sure we don't accidentally add components / attributes and break applications.

**Comment by RWOverdijk** [comment]
Published as 1.1.6!

**Pull request merged**
