### PR TITLE
Fixes issues with typescript typing errors #194

### PR DESCRIPTION
**Pull request by raks-patel**
I was having the same errors as the user that raised the issue #194.  I've removed the offending lines as they seem erroneous. I also made some corrections in a couple of import statements.

### CODE REVIEW

**Comment by raks-patel** [comment]
Sorry i've done this PR in the wrong way.  Just saw your guidelines!  I've made a change to a generated file.

**Comment by jvkassi** [comment]
@raks-patel @RWOverdijk  this PR fix the typescript problem.
Is it possible to merge it ?

**Comment by RWOverdijk** [comment]
@mib4fun It's a generated file, I think it should be fixed elsewhere. If I merge this, the next PR will undo it again.

**Comment by jvkassi** [comment]
Oh okay :man_facepalming:  . Any hints ? How can i do that ?

**Comment by RWOverdijk** [comment]
@mib4fun I'm not entirely sure what this fixes yet, I'd have to check. This file gets auto generated so it's weird to me that it's wrong

**Pull request closed without merging**
