### PR TITLE
fix(fileInput): require attributes and use file binding

### PR DESCRIPTION
**Pull request by edouardmenayde**

### CODE REVIEW

**Comment by edouardmenayde** [comment]
@bas080

**Comment by bas080** [comment]
:+1:
@doktordirk: please merge

**Comment by RWOverdijk** [comment]
Looks good. I'll create an issue for accept types. Or can I pass that in via attributes?

**Comment by bas080** [comment]
@RWOverdijk, as they are part of plain html they can be set using the attributes property.

**Pull request merged**
