### PR TITLE
Fix/checkbox

### PR DESCRIPTION
**Pull request by edouardmenayde**

### CODE REVIEW

**Comment by edouardmenayde** [comment]
@doktordirk or @bas080 :)

**Comment by RWOverdijk** [comment]
@Scrunshes Or me. :)

First things first, don't commit the dist. We create the dist on releases (it's just easier to review that way).

**Comment by edouardmenayde** [comment]
Okay, so I create another branch without build and then new PR ?

**Comment by RWOverdijk** [comment]
Or remove your last commit

**Comment by edouardmenayde** [comment]
@RWOverdijk done :)

**Comment by doktordirk** [comment]
@RWOverdijk 
attributes.js:

``` js
  valueChanged() {
    $(this.element).attr(this.value || {});
  }
```

jquery? is that your intention?

**Comment by bas080** [comment]
The current change looks good to me :+1:

**Comment by RWOverdijk** [comment]
@doktordirk I think that belongs in an issue. Not this PR.

**Pull request merged**
